{
 "title": "Containers Monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Node Exporter/Prometheus) updated from ID 893 by Thibaut Mottet",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "containergroup",
    "label": "Container Group",
    "query": "label_values(node_uname_info, group)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_uname_info{job=\"cominfra-stg\"}, instance)"
   },
   { "name": "environment", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{environment=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",environment=~\"$environment\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",environment=~\"$environment\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{environment=\"$environment\"} - node_memory_MemAvailable_bytes{environment=\"$environment\"}) / node_memory_MemTotal_bytes{environment=\"$environment\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{environment=~\"$environment\"} - node_memory_SwapFree_bytes{environment=~\"$environment\"})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_load1{environment=~\"$environment\"}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{environment=\"$environment\"}[1m])) ",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{environment=~\"$environment\"}[1m])) ",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{environment=~\"$environment\"}",
     "legendFormat": "{{server}}_15m"
    },
    {
     "expr": "node_load5{environment=~\"$environment\"}",
     "legendFormat": "_5m"
    },
    {
     "expr": "node_load15{environment=~\"$environment\"}",
     "legendFormat": "_15m"
    }
   ]
  },
  {
   "title": "Disk Avaliable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\",environment=~\"$environment\"}",
     "legendFormat": "Used Free"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{environment=~\"$environment\"}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\", environment=\"$environment\"}[1m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS IOps per container",
   "type": "timeseries",
   "description": "Disk I/O operations per second for each device",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}} - Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}} - Write"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\"} - container_memory_usage_bytes{name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\"}) ) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}