
services:
  generator-garden-station-1:
    image: ghcr.io/redpanda-data/connect
    command: ["-w", "-c", "/connect.yaml"]
    volumes:
      - ../../benthos/generator.yaml:/connect.yaml
    networks:
      - pathfinder_network_dev
    environment:
      MQTT_PUBLISH_URL: "hivemq:1883"
      MQTT_PUBLISH_TOPIC: home/garden/station/1/environment
      MQTT_PUBLISH_QOS: 1
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

  generator-garden-station-2:
    image: ghcr.io/redpanda-data/connect
    command: ["-w", "-c", "/connect.yaml"]
    volumes:
      - ../../benthos/generator.yaml:/connect.yaml
    networks:
      - pathfinder_network_dev
    environment:
      MQTT_PUBLISH_URL: "hivemq:1883"
      MQTT_PUBLISH_TOPIC: home/garden/station/2/environment
      MQTT_PUBLISH_QOS: 1
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

  generator-living-room:
    image: ghcr.io/redpanda-data/connect
    command: ["-w", "-c", "/connect.yaml"]
    volumes:
      - ../../benthos/generator.yaml:/connect.yaml
    networks:
      - pathfinder_network_dev
    environment:
      MQTT_PUBLISH_URL: "hivemq:1883"
      MQTT_PUBLISH_TOPIC: home/kitchen/stove/1/environment
      MQTT_PUBLISH_QOS: 1
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
