apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: pathfinder
  source:
    repoURL: https://github.com/MGYOSBEL/pathfinder
    targetRevision: devops/setup-k8s-cluster
    path: deploy/cluster/base/apps/networking/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
