apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: pathfinder
  sources:
    - chart: loki
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: "*"  # TODO: pin to a specific version before going to prod
      helm:
        valueFiles:
          - $values/deploy/cluster/base/apps/observability/loki-values.yaml
    - repoURL: https://github.com/MGYOSBEL/pathfinder
      targetRevision: devops/setup-k8s-cluster
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
