apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pathfinder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Pathfinder platform project
  sourceRepos:
    - https://github.com/MGYOSBEL/pathfinder
    - https://grafana.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
    - https://jaegertracing.github.io/helm-charts
    - https://charts.jetstack.io                    # cert-manager
    - oci://docker.io/envoyproxy                    # Envoy Gateway
    - registry-1.docker.io                          # OCI Helm registry
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
