input:
  label: "rabbitmq"
  amqp_0_9:
    urls: ["${RABBITMQ_SUBSCRIBE_URL:localhost:5672}"]
    queue: "${RABBITMQ_SUBSCRIBE_QUEUE}"
    queue_declare:
      enabled: true
      durable: true
      auto_delete: false
    bindings_declare:
      - exchange: "data"
        key: "#"
    auto_ack: false

pipeline:
  processors:
    - bloblang: |
        let value = this.value.number().string()
        let plant = this.plant
        let line = this.line
        let cell = this.cell
        let measurement = this.measurement
        let variable = this.variable
        let timestamp = this.timestamp.ts_unix_milli().string()
        root = "metrics,plant=" + $plant+ ",line=" + $line + ",cell=" + $cell + ",measurement=" + $measurement + " " + $variable + "=" + $value + " " + $timestamp

output:
  type: http_client
  http_client:
    url: http://${INFLUXDB_WRITE_URL}/api/v3/write_lp?db=raw&precision=millisecond&accept_partial=true
    verb: POST
    headers:
      Authorization: Bearer ${INFLUXDB_WRITE_TOKEN}
      Content-Type: text/plain

metrics:
  prometheus:
    use_histogram_timing: true
    histogram_buckets: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 2.5, 5.0, 10.0]

http:
  address: 0.0.0.0:4195
  enabled: true
  root_path: /benthos
  debug_endpoints: false
