input:
  mqtt:
    urls:
      - mqtt://mosquitto:1883
    client_id: benthos-e2e-test
    connect_timeout: 30s
    topics:
      - "#"
    auto_replay_nacks: true

pipeline:
  processors:
    - topic_parser: {}

output:
  stdout:
    codec: lines
