input:
  mqtt:
    urls:
      - "${MQTT_SUBSCRIBE_URL:mqtt://localhost:18883}"
    client_id: benthos-e2e-test
    connect_timeout: 30s
    topics:
      - "#"
    auto_replay_nacks: true

pipeline:
  processors:
    - topic_parser: 
        dsn: "${TOPIC_PARSER_DSN:postgresql://admin:admin@localhost:54432/postgres}"

output:
  stdout:
    codec: lines
