services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  benthos:
    build:
      context: ../../..
      dockerfile: deploy/docker/e2e-tests/Dockerfile
    command: run /config/benthos-config.yaml
    depends_on:
      - mosquitto
      - db
    volumes:
      - ./benthos-config.yaml:/config/benthos-config.yaml:ro

