services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "18883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "54432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql

  benthos:
    build:
      context: ../../..
      dockerfile: deploy/docker/e2e-tests/Dockerfile
    command: run /config/benthos-config.yaml
    environment:
      MQTT_SUBSCRIBE_URL: "mqtt://mosquitto:1883"
      TOPIC_PARSER_DSN: "postgresql://admin:admin@db:5432/postgres"
    depends_on:
      - mosquitto
      - db
    volumes:
      - ./benthos-config.yaml:/config/benthos-config.yaml:ro

