// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PathfinderConfig struct {
	ID             int32              `json:"id"`
	Name           string             `json:"name"`
	Pattern        string             `json:"pattern"`
	Version        string             `json:"version"`
	Enabled        bool               `json:"enabled"`
	Priority       int32              `json:"priority"`
	MetadataConfig []byte             `json:"metadata_config"`
	PayloadConfig  []byte             `json:"payload_config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
