// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const getConfigByName = `-- name: GetConfigByName :one
SELECT id, name, pattern, version, enabled, priority, metadata_config, payload_config
FROM pathfinder_config
WHERE name = $1
LIMIT 1
`

type GetConfigByNameRow struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Pattern        string `json:"pattern"`
	Version        string `json:"version"`
	Enabled        bool   `json:"enabled"`
	Priority       int32  `json:"priority"`
	MetadataConfig []byte `json:"metadata_config"`
	PayloadConfig  []byte `json:"payload_config"`
}

func (q *Queries) GetConfigByName(ctx context.Context, name string) (GetConfigByNameRow, error) {
	row := q.db.QueryRow(ctx, getConfigByName, name)
	var i GetConfigByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pattern,
		&i.Version,
		&i.Enabled,
		&i.Priority,
		&i.MetadataConfig,
		&i.PayloadConfig,
	)
	return i, err
}

const insertConfig = `-- name: InsertConfig :one
INSERT INTO pathfinder_config (name, pattern, version, enabled, priority, metadata_config, payload_config)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, pattern, version, enabled, priority, metadata_config, payload_config
`

type InsertConfigParams struct {
	Name           string `json:"name"`
	Pattern        string `json:"pattern"`
	Version        string `json:"version"`
	Enabled        bool   `json:"enabled"`
	Priority       int32  `json:"priority"`
	MetadataConfig []byte `json:"metadata_config"`
	PayloadConfig  []byte `json:"payload_config"`
}

type InsertConfigRow struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Pattern        string `json:"pattern"`
	Version        string `json:"version"`
	Enabled        bool   `json:"enabled"`
	Priority       int32  `json:"priority"`
	MetadataConfig []byte `json:"metadata_config"`
	PayloadConfig  []byte `json:"payload_config"`
}

func (q *Queries) InsertConfig(ctx context.Context, arg InsertConfigParams) (InsertConfigRow, error) {
	row := q.db.QueryRow(ctx, insertConfig,
		arg.Name,
		arg.Pattern,
		arg.Version,
		arg.Enabled,
		arg.Priority,
		arg.MetadataConfig,
		arg.PayloadConfig,
	)
	var i InsertConfigRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Pattern,
		&i.Version,
		&i.Enabled,
		&i.Priority,
		&i.MetadataConfig,
		&i.PayloadConfig,
	)
	return i, err
}

const listEnabledConfigs = `-- name: ListEnabledConfigs :many
SELECT id, name, pattern, version, enabled, priority, metadata_config, payload_config
FROM pathfinder_config
WHERE enabled = true
ORDER BY priority DESC
`

type ListEnabledConfigsRow struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Pattern        string `json:"pattern"`
	Version        string `json:"version"`
	Enabled        bool   `json:"enabled"`
	Priority       int32  `json:"priority"`
	MetadataConfig []byte `json:"metadata_config"`
	PayloadConfig  []byte `json:"payload_config"`
}

func (q *Queries) ListEnabledConfigs(ctx context.Context) ([]ListEnabledConfigsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledConfigsRow
	for rows.Next() {
		var i ListEnabledConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Pattern,
			&i.Version,
			&i.Enabled,
			&i.Priority,
			&i.MetadataConfig,
			&i.PayloadConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
